fruit = "Strawberry"
print("\nIs fruit == 'Strawberry'? I predict True.")
print(fruit == "Strawberry")
print("Is fruit == 'Watermelon'? I predict False.")
print(fruit == "Watermelon")
print("\nIs fruit.lower() == 'strawberry'? I predict True.")
print(fruit.lower() == "strawberry")
print("Is fruit.lower() == 'Strawberry'? I predict False.")
print(fruit.lower() == "Strawberry")

number = 14
print("\nIs number == 14? I predict True.")
print(number == 14)
print("Is number != 14? I predict False.")
print(number != 14)
print("\nIs number > 13? I predict True.")
print(number > 13)
print("Is number > 14? I predict False.")
print(number > 14)
print("\nIs number < 15? I predict True.")
print(number < 15)
print("Is number < 14? I predict False.")
print(number < 14)
print("\nIs number >= 13? I predict True.")
print(number >= 13)
print("Is number >= 15? I predict False.")
print(number >= 15)
print("\nIs number <= 15? I predict True.")
print(number <= 15)
print("Is number <= 13? I predict False.")
print(number <= 13)

number = 27
print("\nIs number >20 and <30? I predict True.")
print(number > 20 and number < 30)
print("\nIs number >20 and <25? I predict False.")
print(number > 20 and number < 25)

numbers = [14, 27]
print("\nIs number 14 in list? I predict True.")
print(14 in numbers)
print("\nIs number 15 in list? I predict False.")
print(15 in numbers)
print("\nIs number 17 not in list? I predict True.")
print(17 not in numbers)
print("\nIs number 27 not in list? I predict False.")
print(27 not in numbers)
