fruits = ['apple', 'orange', 'banana']
print(f'Number of fruits: {len(fruits)}')
fruits.remove('apple')
print(f'Fruits: {fruits}')
fruits.append('pineapple')
print(f'Fruits: {fruits}')
fruits.insert(0, 'kiwi')
print(f'Fruits: {sorted(fruits)}')
fruits.reverse()
print(f'Fruits: {fruits}')
fruits.sort()
print(f'Fruits: {fruits}')
fruits.pop()
print(f'Fruits: {fruits}')
del fruits[0]
print(f'Fruits: {fruits}')